"""add rag content hash

Revision ID: 03d508aa801f
Revises: 97c2600013bc
Create Date: 2026-09-14 22:50:36.020052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d508aa801f'
down_revision: Union[str, Sequence[str], None] = '97c2600013bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_rag_documents_content_hash'), 'rag_documents', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_documents_content_hash'), table_name='rag_documents')
    op.drop_column('rag_documents', 'content_hash')
    # ### end Alembic commands ###
