"""create customer intelligence

Revision ID: 5203bc37c9c6
Revises: b039ae2cc9b0
Create Date: 2026-09-14 15:57:27.565222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5203bc37c9c6'
down_revision: Union[str, Sequence[str], None] = 'b039ae2cc9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('churn_risk', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('primary_issue', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_intelligence_customer_id'), 'customer_intelligence', ['customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_intelligence_customer_id'), table_name='customer_intelligence')
    op.drop_table('customer_intelligence')
    # ### end Alembic commands ###
