"""create customer interactions

Revision ID: b039ae2cc9b0
Revises: 56c44f124a53
Create Date: 2026-09-10 16:53:30.181229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b039ae2cc9b0'
down_revision: Union[str, Sequence[str], None] = '56c44f124a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index('ix_interactions_customer_occurred', 'customer_interactions', ['customer_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interactions_customer_occurred', table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    # ### end Alembic commands ###
